# Generated by Django 3.2.9 on 2021-11-15 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_1', models.SmallIntegerField(blank=True, null=True)),
                ('score_2', models.SmallIntegerField(blank=True, null=True)),
                ('score_3', models.SmallIntegerField(blank=True, null=True)),
                ('score_4', models.SmallIntegerField(blank=True, null=True)),
                ('score_5', models.SmallIntegerField(blank=True, null=True)),
                ('score_6', models.SmallIntegerField(blank=True, null=True)),
                ('score_1_created_at', models.DateTimeField(blank=True, null=True)),
                ('score_2_created_at', models.DateTimeField(blank=True, null=True)),
                ('score_3_created_at', models.DateTimeField(blank=True, null=True)),
                ('score_4_created_at', models.DateTimeField(blank=True, null=True)),
                ('score_5_created_at', models.DateTimeField(blank=True, null=True)),
                ('score_6_created_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
