# Generated by Django 3.2.9 on 2021-11-16 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='score_4',
        ),
        migrations.RemoveField(
            model_name='score',
            name='score_4_created_at',
        ),
        migrations.RemoveField(
            model_name='score',
            name='score_5',
        ),
        migrations.RemoveField(
            model_name='score',
            name='score_5_created_at',
        ),
        migrations.RemoveField(
            model_name='score',
            name='score_6',
        ),
        migrations.RemoveField(
            model_name='score',
            name='score_6_created_at',
        ),
    ]
