# Generated by Django 3.2.9 on 2021-11-20 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0002_auto_20211116_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='score_4',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='score_4_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
