# Generated by Django 3.2.9 on 2021-11-15 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('score', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docu_integrated', models.CharField(max_length=100)),
                ('cert_web', models.CharField(blank=True, max_length=100, null=True)),
                ('cert_online', models.CharField(blank=True, max_length=100, null=True)),
                ('cert_offline', models.CharField(blank=True, max_length=100, null=True)),
                ('cert_license', models.CharField(blank=True, max_length=100, null=True)),
                ('cert_contest', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('neis_number', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('first_major', models.CharField(max_length=1)),
                ('second_major', models.CharField(default='0', max_length=1)),
                ('school', models.CharField(max_length=30)),
                ('grade', models.CharField(blank=True, max_length=1, null=True)),
                ('_class', models.CharField(blank=True, max_length=2, null=True)),
                ('number', models.CharField(blank=True, max_length=2, null=True)),
                ('tel_st', models.CharField(max_length=11, unique=True)),
                ('tel_pa', models.CharField(max_length=11)),
                ('password', models.CharField(max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='recruit.document')),
                ('score', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='score.score')),
            ],
        ),
    ]
