# Generated by Django 3.2.9 on 2021-11-14 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0003_alter_student_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='neis_number',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
