# Generated by Django 3.2.9 on 2021-11-15 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0003_auto_20211115_0859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='_class',
            new_name='Class',
        ),
    ]
