# Generated by Django 3.2.9 on 2021-11-14 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0004_student_neis_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='first_major',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='second_major',
            field=models.IntegerField(default=0),
        ),
    ]
