# Generated by Django 3.2.9 on 2021-11-14 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0005_auto_20211114_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='first_major',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='second_major',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
