# Generated by Django 3.2.9 on 2021-11-19 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0006_remove_document_cert_web'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='cert_license',
        ),
    ]
